version = 1

test_patterns = ["tests/"]

exclude_patterns = ["rython/jit/__rust__/target/"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[code_formatters]]
name = "rustfmt"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "ruff"